### ISSUE TITLE
Selwyn the Fence incorrectly creates Amber when fighting/reaping

### ISSUE THREAD

**Issue by LeonardQuirm** [jeremylarner/keyteki#80]
Selwyn the Fence (Shadows, #309) reads:

> **Fight/Reap:** Move 1[AE] from one of your cards to your pool.

However, when he was used against me in a game where my opponent had no Amber on any of his cards, Selwyn still generated an additional Amber when Reaping.

I didn't see what would happen if there was any Amber on my opponent's cards - whether this would replace the correct behavior, appear in addition to the correct behavior, or simply not happen when there was Amber to take.

(In case it's relevant - this also occurred on turns when my opponent had reaped with Nexus, allowing him to use my Crystal Mines, so meaning Selwyn's Reap was already producing 2 Amber.  I suspect this is irrelevant to the bug, but logging in case).

**Comment by jeremylarner** [comment]
This should be fixed now

**Comment by DarqXyde** [comment]
I just experienced this issue today. I played against my wife, and I reaped with Selwyn, forcing me to choose a creature. I hadn’t captured any aember, but it reported that it moved an aember off the creature and into my pool. This was in addition to the aember from reaping.

**Comment by tylerSmithTSS** [comment]
This issue is either still happening or started happening again.

**Comment by Jarimy123** [comment]
Yes it definitely is still happening.
